[package]
name = "pass-gui-druid"
version = "0.1.0"
authors = ["mexus <null@mexus.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
